description: The starter theme template of HB (Hugo Bootstrap) Framework.

hb:
  # override SASS variables, please replace the dash with underline, e.g. `list-group-color` should be `list_group_color`.
  # styles:
  #   primary: '#6610f2'
  
  # js_bundle_name: main # the JS bundle name.
  # css_bundle_name: main # the CSS bundle name.
  
  full_width: true # when true, the layout takes full width globally.

  header:
    brand: Mihalt-projects # the brand name, leave it empty to use site's title.
    #logo_bg: '#712cf9' # logo background color, used by logo with transparent background.
    # see https://hbstack.dev/en/docs/modules/socials/.
    socials:
      github: mihalt-projects
      linkedin : evan-staub-bb7570213
  footer:
    # see https://hbstack.dev/en/docs/modules/socials/.
    socials:
      _color: false # when false, remove the color of social icons.
      github: mihalt-projects
      linkedin : evan-staub-bb7570213
  terms:
    # the paginate for categories, tags, series list pages.
    paginate: 12
  blog:
    sidebar:
      profile:
        title: Mihalt-projects # the profile title.
        description: System administration, open resources and more
        company: Haventure / EPSI
        location: Grenoble
        socials:
          github: Mihalt-projects
          linkedin : evan-staub-bb7570213
      posts:
        recent_count: 3 # the number of recent posts.
        featured_count: 3 # the number of featured posts.
      taxonomies:
        count: true # whether to show the number of posts associated to the item.
        limit: 10 # the maximum number of the item.
    paginate: 12 # paginate.
    post_thumbnail_placeholder: HB THEME # the text of thumbnail placeholder, default to site title.
    # post_thumbnail: false # whether to show the thumbnails.
    # post_date_format: ":date_long" # see https://gohugo.io/functions/dateformat/#datetime-formatting-layouts.
    home: # homepage settings.
      taxonomies: false # remove the taxonomies stat from the homepage.
      featured_posts: 3 # the number of the featured posts.
      main_sections: # leave it empty to include all regular pages.
        - docs
        - blog
        - tutorials
  content_panel:
    repo:
      service: github # github or gitlab.
      repo: hbstack/theme
      branch: main
      # subpath: exampleSite
  # gallery:
  #   thumbnail_size: "x640"

seo:
  favicons: # see https://hugomods.com/en/docs/seo/#favicons-module
    icon: images/logo.png # use logo as favicon.

# PWA settings, see https://hugomods.com/en/docs/pwa/#site-parameters.
pwa:
  debug: false
  manifest:
    background_color: '#712cf9'
    theme_color: '#712cf9'
    short_name: 'HB Theme'

# see https://hugomods.com/search/configurations/.
search:
  stall_threshold: 300
  min_match_char_length: 2
  case_sensitive: false
  # shortcut_search: ["/"]

mermaid:
  # replace it with other CDNs or self-hosted URLs.
  js_url: https://cdn.jsdelivr.net/npm/mermaid@latest/dist/mermaid.esm.min.mjs

hugopress:
  modules:
    hb-custom:
      hooks:
        # see layouts/partials/hugopress/modules/hb-custom/hooks/head-end.html.
        head-end:
          cacheable: true
        # see layouts/partials/hugopress/modules/hb-custom/hooks/body-end.html.
        body-end:
          cacheable: true
        # see layouts/partials/hugopress/modules/hb-custom/hooks/hb-blog-sidebar.html.
        hb-blog-sidebar:
          cacheable: true
          weight: 1
    # change the order of sidebar modules.
    hb-blog-sidebar-taxonomies:
      hooks:
        hb-blog-sidebar:
          weight: 3
    hb-blog-sidebar-posts:
      hooks:
        hb-blog-sidebar:
          weight: 2
