[build]
command = "npm ci && hugo --minify --gc -b $URL" # change to suite your needs.
publish = "public"

[build.environment]
NODE_VERSION = "19"
HUGO_VERSION = "0.111.3"
HUGO_ENABLEGITINFO = "true"
HUGO_ENV = "production"
GO_VERSION = "1.20"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "deny"
    X-XSS-Protection = "1; mode=block"

# multilingual 404 pages.
[[redirects]]
  from = "/:lang/*"
  to = "/:lang/404.html"
  status = 404

# fallback 404 page.
[[redirects]]
  from = "/*"
  to = "/en/404.html" # Replace the "en" to your default language code.
  # to = "/404.html" # Use this instead when a monolingual site or "defaultContentLanguageInSubdir" is disabled.
  status = 404
